language: c
compiler:
  - gcc
before_install:
  - sudo apt-get install cmake valgrind
script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make && ./test-entities && valgrind --tool=memcheck --leak-check=full --track-origins=yes -v ./test-entities

